### ISSUE TITLE
Aws nuke process gets stuck and goes into infinite running

### ISSUE THREAD

**Issue by vas-rus** [rebuy-de/aws-nuke#661] opened 2021-07-06 18:25 UTC
I am using my app to run aws nuke commands on terminal. In dry run only they get stuck and goes into never ending loop. Anyone know reason for the nuke process to go in infinite loop. Attaching "ps aux" for the processes. 
<img width="1101" alt="Screenshot 2021-07-06 at 11 47 41 PM" src="https://user-images.githubusercontent.com/63399411/124648997-8e226e00-deb5-11eb-94b0-4f29d1e538dc.png">
Sometimes when I am running these commands direct from terminal , same every word they become successful. So thats also a problem. 

The account has 537 buckets and in running from terminal also it take delays and time but gets successful , but same initiating from app is not working for this aws account , but for others where buckets are 100 odd it is working fine

**Comment by svenwltr** [comment] 2021-07-08 08:00
Sounds like a duplicate of https://github.com/rebuy-de/aws-nuke/issues/613. Please try to exclude S3 Objects:

```yaml
resource-types:
  excludes:
  - S3Object
```

If this does not work try to enable the verbose output (`-v` flag) and look where it gets stuck.

**Comment by vas-rus** [comment] 2021-07-12 08:43
@svenwltr nopes this one is different and exclude filter also doesn't change this strange issue , so process terminal unable to complete this task and that is issue

**Comment by svenwltr** [comment] 2021-07-12 09:35
So what are the last few log lines when it hangs? You can see them when you provide the `-v` flag to aws-nuke.

**Comment by vas-rus** [comment] 2021-07-13 10:19
@svenwltr according to logs it gets completed as last line is  "The above resources would be deleted with the supplied configuration. Provide --no-dry-run to actually destroy resources."  
but then get stuck and doesn't complete. 

<img width="1663" alt="Screenshot 2021-07-13 at 3 44 02 PM" src="https://user-images.githubusercontent.com/63399411/125434908-791a8013-e403-4df7-8ed5-8603a2d9310c.png">

So it is not ending automatically after this point , is this known issue or some resolution exists ?

**Comment by svenwltr** [comment] 2021-07-13 11:21
We never heard of this issue. Could you please kill the process with `SIGQUIT` (eg `kill -SIGQUIT <process-id>`) when it hangs and post the output?

**Comment by FelipeRuizGarcia** [comment] 2022-12-28 17:21
I am seeing this issue with the `aws-nuke-v2.21.2-linux-amd64`

**Comment by FelipeRuizGarcia** [comment] 2022-12-28 17:30
I tried  to exclude S3 Objects but does not work.

```
ERRO[0060] BucketNotEmpty: The bucket you tried to delete is not empty
        status code: 409

```

**Comment by ekristen** [comment] 2024-09-26 23:36
Please give the fork a try at https://github.com/ekristen/aws-nuke, if this is still an issue open an issue there. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Closed by ekristen** 2024-09-26 23:36 UTC
