### ISSUE TITLE
Account has "nonprod" in the title, but is detected by aws-nuke

### ISSUE THREAD

**Issue by zukwung** [rebuy-de/aws-nuke#566] opened 2020-10-20 02:10 UTC
I was testing out aws-nuke and seeing what it can do, and was trying to do that first run following the usage in the readme. However, my account is aliased `aws-orgname-nonprod`, but aws-nuke seems to detect that. Unfortunately, another org in my company manages aws account creation and renaming is not a simple task. Please see the output below: 

```
➜  aws-nuke git:(master) ✗ aws-nuke -c config.yaml --profile orgname_nonprod                                                                                                                                             
aws-nuke version v2.14.0 - Thu Jan 30 13:57:46 UTC 2020 - d9bff8695c3a3e8f72050a76f14ce3f05c07b5c6

Error: You are trying to nuke an account with the alias 'aws-orgname-nonprod', but it has the substring 'prod' in it. Aborting.
```

I checked the code and there doesn't seem to be a workaround as its a simple substring, but I wanted to open this issue to see if there might be somethign that I didn't pick up in the code or docs. Thanks in advance!

**Comment by svenwltr** [comment] 2020-10-20 08:26
Hello. This is a duplicate of https://github.com/rebuy-de/aws-nuke/issues/443

**Closed** 2020-10-20 08:26 UTC

**Comment by zukwung** [comment] 2020-10-20 13:46
@svenwltr thank you, sorry about that. I tried looking for the error message but was unable to find it 😭

**Comment by svenwltr** [comment] 2020-10-20 13:48
That's nothing to be sorry about :)
