### ISSUE TITLE
Please Allow "non-prod" in the account alias

### ISSUE THREAD

**Issue by carlregencia** [rebuy-de/aws-nuke#1118] opened 2023-10-05 09:47 UTC
Unfortunately, I have named my aws non-prod. I want to do a quick cleanup every time I finished a tutorial or training hence I want to use this script.  I hope you can help modify the restriction and allow non-prod on the Alias Name.

**Comment by npellegrin** [comment] 2023-10-15 09:19
Seems to be a duplicate of #997

**Comment by ekristen** [comment] 2024-09-14 01:30
A feature called [Bypass Alias Check](https://ekristen.github.io/aws-nuke/features/bypass-alias-check/) has been implemented in the [now active managed fork of aws-nuke](https://github.com/ekristen/aws-nuke). 

Unfortunately as it stands `prod` is hard coded in. However the bypass alias check allows you to skip alias checks all together when configured.

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Closed by ekristen** 2024-09-14 01:30 UTC
