### ISSUE TITLE
Failure Recorded Even When Deletion Was Successful (CFS)

### ISSUE THREAD

**Issue by mathewlk** [rebuy-de/aws-nuke#334] opened 2019-02-21 18:40 UTC
I just started using aws-nuke, and I get the "CFS might not be deleted after this run" error message for two stacks (1 parent and 1 nested stack). They are then recorded as "failures" when the script terminates. However, when I look in my account all my CloudFormation stacks have been deleted.

I'm just wondering why this is and if it can be handled better? The error is originating from https://github.com/rebuy-de/aws-nuke/blob/master/resources/cloudformation-stack.go#L61. Looks like if the CFS status is not "DeleteFailed", this error will be recorded regardless of whether the previous deletion (line 58) was successful or not. I could be missing something, but shouldn't there be a check before returning an Error (which I assume is the cause of the 2 failures I see at the end of the script run)?

**Comment by mathewlk** [comment] 2019-02-21 18:42
For more context, here is the output of aws-nuke's last iteration:

```
Removal requested: 0 waiting, 2 failed, 39 skipped, 35 finished

us-east-1 - CloudFormationStack - MyStack-333e4f4f79084cf5ba127aebc-VPCNetworkComponentTemplate-ESCDWBSN4BNO - [Name: "MyStack-333e4f4f79084cf5ba127aebc-VPCNetworkComponentTemplate-ESCDWBSN4BNO"] - CFS might not be deleted after this run.
us-east-1 - CloudFormationStack - MyStack-333e4f4f79084cf5ba127aebc4266b08 - [Name: "MyStack-333e4f4f79084cf5ba127aebc4266b08"] - CFS might not be deleted after this run.

Removal requested: 0 waiting, 2 failed, 39 skipped, 35 finished

Error: There are resources in failed state, but none are ready for deletion, anymore.
```

**Comment by svenwltr** [comment] 2019-02-22 09:50
Hello @mathewlk,

it looks like the states in CloudFormation are quite complex. We already iterated a few times over it and I think we need to think to rework it completely.

So, this might take a while.

**Comment by mathewlk** [comment] 2019-02-23 02:31
Ok, good to know, thanks for the response.

**Comment by videte47** [comment] 2019-05-03 02:45
@svenwltr can you share what your thinking here - I am willing to help on this issue

**Comment by svenwltr** [comment] 2019-05-03 11:46
@videte47 I am still not sure about this. We either have to rework the whole resource or look at this issue in particular. For doing the later one we would have to reproduce the issue and improve the CFS listing, so it would not list stacks which are actually already deleted.

**Comment by tylersouthwick** [comment] 2019-11-13 17:59
I reworked the stack deletion in https://github.com/rebuy-de/aws-nuke/pull/424 to address this.

**Comment by ekristen** [comment] 2024-09-27 00:05
Closing due to age. Please test v3 at https://github.com/ekristen/aws-nuke, if still an issue, open an issue there. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Closed by ekristen** 2024-09-27 00:05 UTC
Labels: status/help-wanted, kind/refactoring
