### ISSUE TITLE
AWS SDK V2 Support

### ISSUE THREAD

**Issue by MikeSchouw** [rebuy-de/aws-nuke#1091] opened 2023-08-28 08:22 UTC
AWS SDK V2 has been out for a while now, but I see it's not really implemented yet by aws-nuke, do you want to incorporate it in new Pull Requests from now on? What are your thoughts on this? @der-eismann @svenwltr @bjoernhaeuser

**Comment by der-eismann** [comment] 2023-08-28 10:09
The AWS Go SDK v1 is still in the General Availability phase without any EOL date being mentioned, so we'll continue using it for now. While the new SDK could bring a performance improvement, it would require a massive rewrite for all resources and the underlying logic and AFAIK you can't mix both SDKs.
So we have it on our radar, but no plan to actually migrate this project. Also closing this as a duplicate of #222.

**Closed by der-eismann** 2023-08-28 10:09 UTC
