### ISSUE TITLE
Substring 'prod' in alias does not allow to nuke production account

### ISSUE THREAD

**Issue by gfrid** [rebuy-de/aws-nuke#730] opened 2022-01-19 14:26 UTC
Substring 'prod' in alias does not allow to nuke production account. There should be another safety countermeasure instead.
just aborting is rather limiting the tool, it should have some kind of option to pass it.

for _, alias := range aliases {
		if strings.Contains(strings.ToLower(alias), "prod") {
			return fmt.Errorf("You are trying to nuke an account with the alias '%s', "+
				"but it has the substring 'prod' in it. Aborting.", alias)
		}
	}

**Comment by der-eismann** [comment] 2022-01-19 14:29
While being a valid concern, this has been mentioned before.

Closing as duplicate of https://github.com/rebuy-de/aws-nuke/issues/443

**Closed by der-eismann** 2022-01-19 14:29 UTC
