### ISSUE TITLE
AWS Cognito user pool deletion fails due to deletion protection

### ISSUE THREAD

**Issue by Dania8012** [rebuy-de/aws-nuke#989] opened 2023-05-01 07:43 UTC
Encountered an error when I tried to remove the AWS Cognito User pool due to the enabled deletion protection. The issue becomes even more complex when aws-nuke removes the service role that manages the user pool, which makes removing the pool undoable unless you contact AWS Support to remove it. 

I believe aws-nuke should be updated to disable deletion protection of the user pool before attempting to delete it.

**Comment by CGarces** [comment] 2023-06-21 19:53
Root cause, since october 2022
https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-cognito-console-user-pool-deletion-protection/

**Comment by ekristen** [comment] 2024-09-26 22:21
This has been resolved over at https://github.com/ekristen/aws-nuke

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Closed by ekristen** 2024-09-26 22:21 UTC
