### ISSUE TITLE
Delete all versions in S3 bucket

### ISSUE THREAD

**Issue by sabrehagen** [rebuy-de/aws-nuke#64] opened 2017-12-12 23:23 UTC
Deleting versioned `S3` buckets fails if all versions are not deleted prior to bucket deletion:

```
us-east-2 - S3Bucket - 's3://application-state' - BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.
	status code: 409, request id: 166516D767C46F79, host id: xezvJzBCa84wcRsXRndei9W8Vz9iqDgZZ/Yad5LZfMQL2i9p4LRNfu8wLcR9AMWWCsMJf1A+Sdk=
```

**Comment by svenwltr** [comment] 2017-12-13 07:54
Duplicate of #62.

**Closed by svenwltr** 2017-12-13 07:54 UTC
Labels: duplicate
