### ISSUE TITLE
Lookup mobile.eu-central-1.amazonaws.com on 127.0.0.53:53: no such host

### ISSUE THREAD

**Issue by leflamm** [rebuy-de/aws-nuke#202] opened 2018-06-19 12:27 UTC
Hi,

when I try to nuke an AWS account I get this output at the end of the scan for resources:

```
ERRO[0031] Listing MobileProject failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
    !!! RequestError: send request failed
    !!! caused by: Get https://mobile.eu-central-1.amazonaws.com/projects?maxResults=100: dial tcp: lookup mobile.eu-central-1.amazonaws.com on 127.0.0.53:53: no such host 
```
```
$ nmap 127.0.0.53 -p53

Starting Nmap 7.60 ( https://nmap.org ) at 2018-06-19 14:20 CEST
Nmap scan report for localhost (127.0.0.53)
Host is up (0.00012s latency).

PORT   STATE SERVICE
53/tcp open  domain
```

```
$ host mobile.eu-central-1.amazonaws.com
Host mobile.eu-central-1.amazonaws.com not found: 3(NXDOMAIN)
```
Seems like I cannot resolve that Host. Should I?

**Comment by tomvachon** [comment] 2018-06-19 13:21
You have a local DNS resolver, 127.0.0.0/8 is your computer, see [RFC5735]( https://tools.ietf.org/html/rfc5735#section-3)

With that out of the way, what version of aws-nuke are you running?  These errors are handled better in v2.0.0 or higher as not all services exist in all places

**Comment by leflamm** [comment] 2018-06-19 13:36
aws-nuke-v2.0.1-linux-amd64

**Comment by tomvachon** [comment] 2018-06-19 16:28
OK, so the 127.0.0.1 is a red herring.  @svenwltr I thought we handled this exception now with a combo of endpoint lookup and regex?

**Comment by tomvachon** [comment] 2018-06-19 16:29
@leflamm this error is begin, no issue but we should be catching them

**Comment by svenwltr** [comment] 2018-06-20 08:52
This error still appears with the most current AWS SDK. The only thing we could do, is to make the error look less fatal, when a DNS lookup fails.

**Comment by svenwltr** [comment] 2018-06-20 09:06
This is a duplicate of #154. Let's keep the discussion there.

**Closed by svenwltr** 2018-06-20 09:06 UTC
Labels: kind/bug
