### ISSUE TITLE
Add an option to exclude any resource with a specific tag

### ISSUE THREAD

**Issue by liyaka** [rebuy-de/aws-nuke#796] opened 2022-05-14 17:55 UTC
It would be nice to have an option to exclude any resource that has a specific tag, for example, I want to exclude any resource that was created by my terraform and has a tag:
- property: "tag:Terraform"
   value: "true"

**Comment by lucasff** [comment] 2022-05-28 12:50
Omg yes please, just came looking for that!

**Comment by svenwltr** [comment] 2022-05-30 08:04
Hello. This is hard to do correctly, because not all resources support tags. And even if we add reliable tag support to all resources, there would be still virtual resources (like EC2VolumeAttachments) that cannot get tagged on AWS side and would always get deleted. And it would not be helpful to make aws-nuke filter an EC2 instances and their EC2 Volume while deleting the attachment between these two.

Also this seems to be a duplicate of https://github.com/rebuy-de/aws-nuke/issues/186

**Comment by scones** [comment] 2023-03-31 14:57
i think there are two misconceptions here, that unnecessarily increase the complexity:

1) some resources can't be tagged, so the nuke would have to start calculate all the dependencies, so this feature is huge, so it will not be done.

as a fan of the proposed feature: i don't care if 10% of the resources are untaggable, when i can skip 90% of the other resources. i can manually exclude the other 10% by hand


2) the tag is anything more than a simple flag, (ie timestamp with comparison)

while a time flag with comparison might be nice, in some cases, a simple "keep this resource"-flag is the major use case for me, and possibly others.
one could extend it to time flags later if there is enough support for that. but in a separate feature.

**Comment by ekristen** [comment] 2024-09-13 01:08
@scones @liyaka @lucasff [Global Filters](https://ekristen.github.io/aws-nuke/config-filtering/#global) has been implemented in my fork which has become the active fork and successor to this amazing project. Please take a look.

If you should run into any issues, please open an issue over there.

----

Please see a copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Closed by ekristen** 2024-09-13 01:08 UTC
