### ISSUE TITLE
fatal error: runtime: out of memory - while running AWS Nuke

### ISSUE THREAD

**Issue by Johnsonkdavid** [rebuy-de/aws-nuke#559] opened 2020-09-16 12:55 UTC
Hi folks,
I configured aws-nuke to wipe out one of my aws accounts in a T3.Large aws Linux VM .Configurations was perfect and when I tried to run the nuke command,it listed some of my resources and then got some error as mentioned below:
" fatal error: runtime: out of memory " - When I check my VM memory, I can see that nuke tooks almost all memory. Can we limit the memory consumption?

I have tried to use few resources like S3Bucket and Lambda under the "targets" option in nuke-config file and it was working fine.The issue is while describing all the services without and exception.

Is there any fix for this?

**Comment by Johnsonkdavid** [comment] 2020-09-18 14:17
I got a small hint why it caused OOM issue for me - I had some s3 bins where I had last few years logs stored.I found that nuke was going through each and every objects in those S3 buckets and that caused an OOM issue for me. I tried to empty one bucket explicitly and ran again the nuke and it was working fine at that moment.

**Comment by svenwltr** [comment] 2020-09-21 08:14
Hello. As you already noticed, this is a duplicate of https://github.com/rebuy-de/aws-nuke/issues/415. Unfortunately there are no easy fixes for this.

**Closed by svenwltr** 2020-09-21 08:14 UTC
