### ISSUE TITLE
aws-nuke with --profile don't work anymore

### ISSUE THREAD

**Issue by youwalther65** [rebuy-de/aws-nuke#419] opened 2019-10-15 11:18 UTC
I am running v2.12.0

```
$ ./aws-nuke version
version:     v2.12.0
build date:  Thu Oct 10 08:42:19 UTC 2019
scm hash:    7f342afcb14a656624fe4176ba9153eaeb38a7a5
environment: root@3a765d393e0b
```

My AWS profiles are fien and work with AWS CLI. Example:

```
[you@localhost .aws]$ aws --profile TestAdmin iam list-roles --query 'Roles[].RoleName'
[
    "AWSBackupDefaultServiceRole",
    "AWSServiceRoleForAmazonGuardDuty",
    "AWSServiceRoleForAmazonInspector",
    "AWSServiceRoleForOrganizations",
    "AWSServiceRoleForSecurityHub",
    "AWSServiceRoleForSupport",
...
]
```

But when I try to use this profile for "aws-nuke" I getthe following error:

```
$ ./aws-nuke -v -c TestAccount-nuke.yml --profile TestAdmin
DEBU[0000] creating new session in us-east-1
DEBU[0000] creating new root session in us-east-1
Error: failed to create default session in us-east-1: CredentialRequiresARNError: credential type source_profile requires role_arn, profile default
```

But it works with for exampel v2.9.0

```
./aws-nuke-v2.9.0-linux-amd64 -c TestAccount-nuke.yml --profile TestAdmin
Assume Role MFA token code: xxx
```

**Comment by youwalther65** [comment] 2019-10-18 14:08
I this context I mean a profile which  assumes a  x-account role and migth require MFA. 
A profile referencing a local IAM user is just fine!

**Comment by svenwltr** [comment] 2019-11-15 10:04
@youwalther65 Sorry for the late response. It is quite hard so figure our what there error is without being able to reproduce it. Looking into to internet tells me, that this might got fixed with the AWS SDK update. Is it working with *aws-nuke* `v2.12.0`? If not, can you show us the `TestAdmin` profile and the profile it is referring to?

**Comment by youwalther65** [comment] 2019-11-20 07:11
@svenwltr Hi Sven/team, I am currently using:

(AWS) [you@localhost Dev]$ aws --version
aws-cli/1.16.286 Python/3.6.3 Linux/3.10.0-957.5.1.el7.x86_64 botocore/1.13.22

07:05 $ ./aws-nuke version
version:     v2.13.0
build date:  Tue Nov 12 09:49:44 UTC 2019
scm hash:    d38e638952b4ce61ab619bc7aa9918c1c0f46a0e
environment: root@2105cd445cd3

The profile used is a x-account MFA enabled role-based profile:

[you@localhost .aws]$ cat credentials
[default]
aws_access_key_id = AKIAxxxx
aws_secret_access_key = ZZZ
...

[you@localhost .aws]$ cat config
[default]
output = json
region = eu-west-1
source_profile = default
get_session_token_duration_seconds=3600
...
[profile SandboxAdmin]
role_arn = arn:aws:iam::yyy:role/ProserviaAccountAdmin.role
source_profile = default
mfa_serial = arn:aws:iam::xxx:mfa/jens-uwe.walther

So this profile contains a role ARN 
07:07 $ ./aws-nuke --profile SandboxAdmin -c SandboxAccount-nuke.yml
Error: failed to create default session in us-east-1: CredentialRequiresARNError: credential type source_profile requires role_arn, profile default

So the error message of AWS-nuke is misleading. I have not set any AWS_xxx enviroment variables because it seems aws-nuke ignores them anyway.
Hop ethi shelps - let me know.

**Comment by svenwltr** [comment] 2019-11-21 09:46
Hello @youwalther65. Why does your `default` profile has a `source_profile` that points to itself? Can you try to remove the line and try again?

**Comment by youwalther65** [comment] 2019-11-21 11:17
Hi @svenwltr You are completely right - my fault, apologize. aws-nuke is the 1st program that struggels at this line ;-)

11:14 $ ./aws-nuke --profile SandboxAdmin -c SandboxAccount-nuke.yml
Assume Role MFA token code: xxxx
aws-nuke version v2.13.0 - Tue Nov 12 09:49:44 UTC 2019 - d38e638952b4ce61ab619bc7aa9918c1c0f46a0e

Do you really want to nuke the account with the ID YYYand the alias 'zzz'?
Do you want to continue? Enter account alias to continue.

Pls go ahead an close the issue!

**Comment by svenwltr** [comment] 2019-11-21 11:18
We are basically passing the parameters down to the AWS SDK. Not sure why it fails here when the CLI does not. Probably a difference in the implementation, since the CLI uses Python.

**Closed by svenwltr** 2019-11-21 11:18 UTC
