### ISSUE TITLE
Listing MQBroker failed

### ISSUE THREAD

**Issue by vhadianto** [rebuy-de/aws-nuke#180] opened 2018-04-17 14:14 UTC
Hi,

Received the following error when using aws-nuke (binary release).

Version: aws-nuke-v2.0.0.alpha1-darwin-amd64

Error message: 
```ERRO[0176] Listing MQBroker failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
    !!! RequestError: send request failed
    !!! caused by: Get https://mq.ap-northeast-1.amazonaws.com/v1/brokers?maxResults=100: dial tcp 92.242.132.24:443: getsockopt: connection refused 
```

**Comment by tomvachon** [comment] 2018-04-19 14:06
@svenwltr isnt this related to the endpoint issues we have seen?

**Comment by svenwltr** [comment] 2018-04-19 14:10
@tomvachon I am not sure, since we usually get something like "no such host" in these cases. We should see, if we can reproduce this, first.

**Comment by svenwltr** [comment] 2018-04-23 12:59
Hello @vhadianto. Thank you for the issue. Are you still getting this error message? Maybe it was just a network hiccup.

**Comment by svenwltr** [comment] 2018-04-25 11:48
Ok, then I will close this for now. Please reopen, if it happens again.

**Closed by svenwltr** 2018-04-25 11:48 UTC
