### ISSUE TITLE
CloudWatchLogsLogGroup - stuck waiting

### ISSUE THREAD

**Issue by mbergal-idx** [rebuy-de/aws-nuke#500] opened 2020-04-30 01:25 UTC
```
/aws/eks/idx-eks-pulumi-test-eksCluster-6586a80/cluster - waiting Removal requested: 1 waiting, 0 failed, 74 skipped, 95 finished 
us-east-2 - CloudWatchLogsLogGroup - /aws/eks/idx-eks-pulumi-test-eksCluster-6586a80/cluster - waiting Removal requested: 1 waiting, 0 failed, 74 skipped, 95 finished
```
Not sure what to add, but I able to delete this log group manually

**Comment by mbergal-idx** [comment] 2020-04-30 03:35
Maybe because when request to delete it is made, EKS cluster is still writing to it?

**Comment by rbbrasil** [comment] 2020-05-05 20:30
@mbergal-idx which release are you running?

I've just got this problem with the v2.14.0. With v2.14.0 the removal went fine.

```
ap-southeast-2 - CloudWatchLogsLogGroup - /aws/vpc/mgmt-VPC/flow-logs - waiting

Removal requested: 1 waiting, 0 failed, 68 skipped, 0 finished

ap-southeast-2 - CloudWatchLogsLogGroup - /aws/vpc/mgmt-VPC/flow-logs - removed

Removal requested: 0 waiting, 0 failed, 68 skipped, 1 finished`

**Comment by rajivchirania** [comment] 2020-05-12 14:11
@mbergal-idx Your above comment contains the same version..
I am also using the version  v2.14.0 and having the same problem with eks cluster deletion and cloudwatch log group deletion..

**Comment by rbbrasil** [comment] 2020-05-12 16:40
Oops! That was a typo. Sorry.

The Docker image version that worked for me was 2.12.0.

**Comment by mbergal-idx** [comment] 2020-05-12 18:19
I am using 2.14.0, deleting single log group works fine, but if log group is associated with the cluster it does not get deleted for some reason.

**Comment by svenwltr** [comment] 2020-05-25 13:18
Hello.

Sorry for the late response. Can you give us a hint to to reproduce this error?

**Comment by mbergal-idx** [comment] 2020-05-27 05:28
This happens if this is EKS cluster's log group. I think it gets deleted but cluster recreates it since it takes more time for it to get deleted. If this is not enough I might be able to create a simple pulumi script to make a repro.

**Comment by rickepnet** [comment] 2020-06-17 00:08
I have the same issue EKS cluster create a cloudwatch log group if I delete the log group by hand it deletes just fine. v2.13.0 I will try to upgrade see if it helps.

**Comment by effektd** [comment] 2021-02-07 23:14
+1 on this issue. Restarting the tool against the account in question, the log group is successfully deleted no problems.

This is a bit of an issue when using automation as the tool will simply recycle the deletion process and continue to fail. Not sure if I can set a retry count and exit with error or not but that would be preferable.

v2.14.0 is the version I am using, also in ap-southeast-2 region.

**Comment by artem-nefedov** [comment] 2021-03-11 08:08
We're also seeing this issue, and it's also caused by EKS log groups.

**Comment by svenwltr** [comment] 2021-03-26 12:58
>  I think it gets deleted but cluster recreates it since it takes more time for it to get deleted.

I follow this idea. Unfortunately I do not see a obvious solution to this.

**Comment by ivan-sukhomlyn** [comment] 2021-07-07 10:36
I have the same situation with the `2.15` version.
CW Log Group is in a stuck state.
Logs:
```
13:35:15  us-west-2 - CloudWatchLogsLogGroup - /aws/eks/{ cluster_name }/cluster - waiting
13:35:15  
13:35:15  Removal requested: 1 waiting, 0 failed, 147 skipped, 64 finished
13:35:15  
13:35:20  us-west-2 - CloudWatchLogsLogGroup - /aws/eks/{ cluster_name }/cluster - waiting
13:35:20  
13:35:20  Removal requested: 1 waiting, 0 failed, 147 skipped, 64 finished
13:35:20  
13:35:25  us-west-2 - CloudWatchLogsLogGroup - /aws/eks/{ cluster_name }/cluster - waiting
13:35:25  
13:35:25  Removal requested: 1 waiting, 0 failed, 147 skipped, 64 finished
```

**Comment by wushingmushine** [comment] 2022-05-31 14:09
Still seeing aws-nuke (v 2.17) indefinitely hanging when deleting cloudwatch log groups. If I cancel the aws-nuke run and re-run, the log group deletes immediately without issue. 

This is unrelated to EKS for me.

Recreate using boto3 to create log group:
```            log_group_response = self.logs.create_log_group(
                logGroupName='rejected-traffic'
            )
```
in eu-west-1 in a completely wiped account. The log group is then targeted by a flow log on the default VPC.
Then running aws-nuke gives 

```
Removal requested: 1 waiting, 0 failed, 296 skipped, 21 finished

eu-west-1 - CloudWatchLogsLogGroup - all-rejected-traffic - waiting

Removal requested: 1 waiting, 0 failed, 296 skipped, 21 finished

eu-west-1 - CloudWatchLogsLogGroup - all-rejected-traffic - waiting

Removal requested: 1 waiting, 0 failed, 296 skipped, 21 finished

eu-west-1 - CloudWatchLogsLogGroup - all-rejected-traffic - waiting
```

It seems aws-nuke is getting stuck in some indefinite cycle?

**Comment by leiarenee** [comment] 2023-05-06 04:44
Infinitely waiting aws-nuke version 2.22.1 
```shell
global - IAMVirtualMFADevice - arn:aws:iam::143749165737:mfa/Leia_Phone - failed
eu-west-1 - CloudWatchEventsRule - Rule: AutoScalingManagedRule - failed
eu-west-1 - CloudWatchLogsLogGroup - /aws/eks/otomi/cluster - [CreatedTime: "1683342110183", LastEvent: "2023-05-06T06:20:34+02:00", logGroupName: "/aws/eks/otomi/cluster", tag:created_by: "terragrunt", tag:k8s: "custom", tag:workspace: "testing"] - waiting
eu-west-1 - CloudWatchEventsTarget - Rule: AutoScalingManagedRule Target ID: autoscaling - waiting

Removal requested: 2 waiting, 2 failed, 93 skipped, 181 finished
```

**Comment by chronicc** [comment] 2023-06-05 09:59
Still failing with v2.22.1.15.ge45750a

```shell
eu-central-1 - CloudWatchEventsRule - Rule: AutoScalingManagedRule - failed
eu-central-1 - CloudWatchEventsTarget - Rule: AutoScalingManagedRule Target ID: autoscaling - waiting

Removal requested: 1 waiting, 1 failed, 557 skipped, 1387 finished
```

**Comment by martivo** [comment] 2023-07-06 12:50
Still same issue, using:
`
quay.io/rebuy/aws-nuke:v2.23.0
`
I have two eks clusters, each have one CloudWatchLogsLogGroup. One of them always gets deleted, the other stays in infinite loop.

**Comment by nileshgadgi** [comment] 2023-09-23 19:06
I am facing the same issue also, my github workflow took 6 hour to delete the resources,
It automatically got cancelled due to default timeout, it was stuck in the CloudWatchLogGroup Deletion. 

Github action gives 3000 minutes free for free organization account and I'm getting the same error every time and I have to compromise with github time limits.

```
eu-west-1 - CloudWatchEventsTarget - Rule: AutoScalingManagedRule Target ID: autoscaling - waiting
eu-west-1 - CloudWatchEventsRule - Rule: AutoScalingManagedRule - waiting
eu-west-1 - CloudWatchLogsLogGroup - /aws/eks/eks-velero-cluster/cluster - [CreatedTime: "1695364752907", LastEvent: "2023-09-22T22:38:20Z", logGroupName: "/aws/eks/eks-velero-cluster/cluster", tag:Environment: "velero", tag:Managedby: "hello@clouddrove.com", tag:Name: "eks-velero-cluster", tag:Repository: "https://github.com/clouddrove/terraform-aws-eks"] - waiting

Removal requested: 3 waiting, 0 failed, 930 skipped, 105 finished

eu-west-1 - CloudWatchEventsTarget - Rule: AutoScalingManagedRule Target ID: autoscaling - waiting
eu-west-1 - CloudWatchEventsRule - Rule: AutoScalingManagedRule - waiting
eu-west-1 - CloudWatchLogsLogGroup - /aws/eks/eks-velero-cluster/cluster - [CreatedTime: "1695364752907", LastEvent: "2023-09-22T22:38:20Z", logGroupName: "/aws/eks/eks-velero-cluster/cluster", tag:Environment: "velero", tag:Managedby: "hello@clouddrove.com", tag:Name: "eks-velero-cluster", tag:Repository: "https://github.com/clouddrove/terraform-aws-eks"] - waiting

Removal requested: 3 waiting, 0 failed, 930 skipped, 105 finished

eu-west-1 - CloudWatchEventsTarget - Rule: AutoScalingManagedRule Target ID: autoscaling - waiting
eu-west-1 - CloudWatchEventsRule - Rule: AutoScalingManagedRule - waiting
eu-west-1 - CloudWatchLogsLogGroup - /aws/eks/eks-velero-cluster/cluster - [CreatedTime: "1695364752907", LastEvent: "2023-09-22T22:38:20Z", logGroupName: "/aws/eks/eks-velero-cluster/cluster", tag:Environment: "velero", tag:Managedby: "hello@clouddrove.com", tag:Name: "eks-velero-cluster", tag:Repository: "https://github.com/clouddrove/terraform-aws-eks"] - waiting

Removal requested: 3 waiting, 0 failed, 930 skipped, 105 finished

eu-west-1 - CloudWatchEventsTarget - Rule: AutoScalingManagedRule Target ID: autoscaling - waiting
eu-west-1 - CloudWatchEventsRule - Rule: AutoScalingManagedRule - waiting
eu-west-1 - CloudWatchLogsLogGroup - /aws/eks/eks-velero-cluster/cluster - [CreatedTime: "1695364752907", LastEvent: "2023-09-22T22:38:20Z", logGroupName: "/aws/eks/eks-velero-cluster/cluster", tag:Environment: "velero", tag:Managedby: "hello@clouddrove.com", tag:Name: "eks-velero-cluster", tag:Repository: "https://github.com/clouddrove/terraform-aws-eks"] - waiting

Removal requested: 3 waiting, 0 failed, 930 skipped, 105 finished

eu-west-1 - CloudWatchEventsTarget - Rule: AutoScalingManagedRule Target ID: autoscaling - waiting
eu-west-1 - CloudWatchEventsRule - Rule: AutoScalingManagedRule - waiting
eu-west-1 - CloudWatchLogsLogGroup - /aws/eks/eks-velero-cluster/cluster - [CreatedTime: "1695364752907", LastEvent: "2023-09-22T22:38:20Z", logGroupName: "/aws/eks/eks-velero-cluster/cluster", tag:Environment: "velero", tag:Managedby: "hello@clouddrove.com", tag:Name: "eks-velero-cluster", tag:Repository: "https://github.com/clouddrove/terraform-aws-eks"] - waiting

Removal requested: 3 waiting, 0 failed, 930 skipped, 105 finished

eu-west-1 - CloudWatchEventsTarget - Rule: AutoScalingManagedRule Target ID: autoscaling - waiting
eu-west-1 - CloudWatchEventsRule - Rule: AutoScalingManagedRule - waiting
eu-west-1 - CloudWatchLogsLogGroup - /aws/eks/eks-velero-cluster/cluster - [CreatedTime: "1695364752907", LastEvent: "2023-09-22T22:38:20Z", logGroupName: "/aws/eks/eks-velero-cluster/cluster", tag:Environment: "velero", tag:Managedby: "hello@clouddrove.com", tag:Name: "eks-velero-cluster", tag:Repository: "https://github.com/clouddrove/terraform-aws-eks"] - waiting

Removal requested: 3 waiting, 0 failed, 930 skipped, 105 finished

eu-west-1 - CloudWatchEventsTarget - Rule: AutoScalingManagedRule Target ID: autoscaling - waiting
eu-west-1 - CloudWatchEventsRule - Rule: AutoScalingManagedRule - waiting
eu-west-1 - CloudWatchLogsLogGroup - /aws/eks/eks-velero-cluster/cluster - [CreatedTime: "1695364752907", LastEvent: "2023-09-22T22:38:20Z", logGroupName: "/aws/eks/eks-velero-cluster/cluster", tag:Environment: "velero", tag:Managedby: "hello@clouddrove.com", tag:Name: "eks-velero-cluster", tag:Repository: "https://github.com/clouddrove/terraform-aws-eks"] - waiting

Removal requested: 3 waiting, 0 failed, 930 skipped, 105 finished
```

![image](https://github.com/rebuy-de/aws-nuke/assets/115100281/eafbd1c8-176f-4574-9136-69ea2d34d73e)

**Comment by ekristen** [comment] 2024-09-27 00:06
Closing due to age. Please test v3 at https://github.com/ekristen/aws-nuke, if still an issue, open an issue there. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Closed by ekristen** 2024-09-27 00:06 UTC

**Comment by ivan-sukhomlyn** [comment] 2024-09-27 07:44
@ekristen thanks for the info and for taking care of the project! 🥇
