### ISSUE TITLE
CloudFront distribution needs to be disabled

### ISSUE THREAD

**Issue by boynux** [rebuy-de/aws-nuke#325] opened 2019-02-04 15:00 UTC
Using AWS Nuke, we encountered this error:

`global - CloudFrontDistribution - Exxxxxxxxxxxxx - DistributionNotDisabled: The distribution you are trying to delete has not been disabled.`

Shouldn't Nuke disable CF distribution before trying to delete it or did we hit some sort of bug?

**Comment by svenwltr** [comment] 2019-02-08 13:05
It actually disables the distribution. What does your configuration look like and what version are you using?

**Comment by mseiwald** [comment] 2019-02-18 06:29
We were on v2.5.0.29.gf7c3d82 but upgraded to v2.7.0 now. We cannot reproduce this right now, so will close the issue. Thank you.

**Closed** 2019-02-22 14:26 UTC
Labels: status/waiting-reponse

**Comment by wdalmut** [comment] 2020-11-11 19:15
in version 2.14.0 

```
version:     v2.14.0
build date:  Thu Jan 30 13:57:34 UTC 2020
scm hash:    d9bff8695c3a3e8f72050a76f14ce3f05c07b5c6
environment: root@3bab39a3ac52
```

the nuke command fails with

```
ERRO[0276] There are resources in failed state, but none are ready for deletion, anymore. 

global - CloudFrontDistribution - EJ8POXXXXXXXX - failed
ERRO[0276] DistributionNotDisabled: The distribution you are trying to delete has not been disabled.
        status code: 409, request id: 521b837d-XXXX-XXXX-XXXX-XXXXXXXXXXXX 
global - CloudFrontDistributionDeployment - EJ8POXXXXXXXX - failed
ERRO[0276] IllegalUpdate: You cannot update the specified distribution using this API version because it is associated with a cache policy.
        status code: 400, request id: d7f83e17-XXXX-XXXX-XXXX-XXXXXXXXXXXX 
```

Maybe also because the new cache policy mechanism?
