### ISSUE TITLE
aws-nuke is trying to remove AWS provided Opensearch Packages (OSPackage)

### ISSUE THREAD

**Issue by venkatamutyala** [rebuy-de/aws-nuke#1123] opened 2023-10-17 08:29 UTC
<img width="549" alt="image" src="https://github.com/rebuy-de/aws-nuke/assets/6570292/0b11d877-66f5-4b7f-aa59-67798e393936">

Given these are defaults by AWS and cannot be deleted, shouldn't they be getting filtered out? I took a quick look at the code and noticed there isn't any func filter() like i've observed with other resources:
https://github.com/rebuy-de/aws-nuke/blob/c703c4346dcff278abd6072d8d72d9be4e911034/resources/opensearchservice-packages.go#L11

Given this was just working a day ago, I am thinking AWS may have made an upstream API change and now nuke is unable to handle new response. Our team observed this error being introduced in the last 24 hours. So I imagine it was a recent change with AWS. Here is the configuration file we typically use:

```yaml
account-blocklist:
- "0123456789"
accounts:
  12345678910:
    presets:
      - common
  
presets:
  common:
    filters:
      IAMRole:
      - type: regex
        value: '.*OrganizationAccountAccessRole.*'
      IAMRolePolicyAttachment:
      - type: regex
        value: '.*OrganizationAccountAccessRole.*'
      OpsWorksUserProfile:
      - type: regex
        value: '.*OrganizationAccountAccessRole.*'



regions:
- global
- us-west-2
- us-east-1
```

2023-10-21 Edit: Here is the work around I am using: https://github.com/rebuy-de/aws-nuke/issues/1123#issuecomment-1766400410

**Comment by morremeyer** [comment] 2023-10-17 13:17
I can reproduce this on our setup. (read: we're running into the same error).

For now, we've added to our config to work around this:

```
resource-types:
  excludes:
    # don't nuke OpenSearch Packages, see https://github.com/rebuy-de/aws-nuke/issues/1123
    - OSPackage
```

Copy-able log output:

```
us-east-1 - OSPackage - G130336370 - [CreatedTime: "2023-10-12T21:10:31Z", PackageID: "G130336370", PackageName: "analysis-sudachi"] - failed
us-east-1 - OSPackage - G132321210 - [CreatedTime: "2023-10-12T20:35:13Z", PackageID: "G132321210", PackageName: "analysis-pinyin"] - failed
us-east-1 - OSPackage - G156166197 - [CreatedTime: "2023-10-12T20:25:27Z", PackageID: "G156166197", PackageName: "analysis-pinyin"] - failed
us-east-1 - OSPackage - G16029449 - [CreatedTime: "2023-10-12T23:26:14Z", PackageID: "G16029449", PackageName: "analysis-nori"] - failed
us-east-1 - OSPackage - G160822909 - [CreatedTime: "2023-10-12T20:40:42Z", PackageID: "G160822909", PackageName: "analysis-stconvert"] - failed
us-east-1 - OSPackage - G174516212 - [CreatedTime: "2023-10-12T23:32:26Z", PackageID: "G174516212", PackageName: "analysis-sudachi"] - failed
us-east-1 - OSPackage - G176501052 - [CreatedTime: "2023-10-12T20:37:30Z", PackageID: "G176501052", PackageName: "analysis-pinyin"] - failed
us-east-1 - OSPackage - G196105221 - [CreatedTime: "2023-10-12T20:14:35Z", PackageID: "G196105221", PackageName: "analysis-nori"] - failed
us-east-1 - OSPackage - G198361199 - [CreatedTime: "2023-10-12T20:55:35Z", PackageID: "G198361199", PackageName: "analysis-sudachi"] - failed
us-east-1 - OSPackage - G205002751 - [CreatedTime: "2023-10-12T20:46:57Z", PackageID: "G205002751", PackageName: "analysis-stconvert"] - failed
us-east-1 - OSPackage - G208725732 - [CreatedTime: "2023-10-16T20:57:30Z", PackageID: "G208725732", PackageName: "amazon-personalized-ranking"] - failed
us-east-1 - OSPackage - G218696054 - [CreatedTime: "2023-10-12T21:04:33Z", PackageID: "G218696054", PackageName: "analysis-sudachi"] - failed
us-east-1 - OSPackage - G240285063 - [CreatedTime: "2023-10-12T20:16:33Z", PackageID: "G240285063", PackageName: "analysis-nori"] - failed
us-east-1 - OSPackage - G249182593 - [CreatedTime: "2023-10-12T20:47:58Z", PackageID: "G249182593", PackageName: "analysis-stconvert"] - failed
us-east-1 - OSPackage - G24926979 - [CreatedTime: "2023-10-12T23:45:09Z", PackageID: "G24926979", PackageName: "analysis-stconvert"] - failed
us-east-1 - OSPackage - G39874436 - [CreatedTime: "2023-10-12T20:12:49Z", PackageID: "G39874436", PackageName: "analysis-nori"] - failed
us-east-1 - OSPackage - G4592124 - [CreatedTime: "2023-10-12T22:47:55Z", PackageID: "G4592124", PackageName: "analysis-stconvert"] - failed
us-east-1 - OSPackage - G60209291 - [CreatedTime: "2023-10-12T20:23:31Z", PackageID: "G60209291", PackageName: "analysis-nori"] - failed
us-east-1 - OSPackage - G86156528 - [CreatedTime: "2023-10-12T22:54:58Z", PackageID: "G86156528", PackageName: "analysis-sudachi"] - failed
us-east-1 - OSPackage - G88141368 - [CreatedTime: "2023-10-12T20:31:16Z", PackageID: "G88141368", PackageName: "analysis-pinyin"] - failed
eu-central-1 - OSPackage - G10042800 - [CreatedTime: "2023-10-12T18:45:41Z", PackageID: "G10042800", PackageName: "analysis-sudachi"] - failed
eu-central-1 - OSPackage - G117378501 - [CreatedTime: "2023-10-12T18:37:33Z", PackageID: "G117378501", PackageName: "analysis-stconvert"] - failed
eu-central-1 - OSPackage - G127912992 - [CreatedTime: "2023-10-12T18:46:20Z", PackageID: "G127912992", PackageName: "analysis-nori"] - failed
eu-central-1 - OSPackage - G140010755 - [CreatedTime: "2023-10-12T18:29:21Z", PackageID: "G140010755", PackageName: "analysis-stconvert"] - failed
eu-central-1 - OSPackage - G147769807 - [CreatedTime: "2023-10-12T18:26:20Z", PackageID: "G147769807", PackageName: "analysis-pinyin"] - failed
eu-central-1 - OSPackage - G162643009 - [CreatedTime: "2023-10-12T18:51:40Z", PackageID: "G162643009", PackageName: "analysis-stconvert"] - failed
eu-central-1 - OSPackage - G164862144 - [CreatedTime: "2023-10-16T20:09:50Z", PackageID: "G164862144", PackageName: "amazon-personalized-ranking"] - failed
eu-central-1 - OSPackage - G16714158 - [CreatedTime: "2023-10-12T18:41:50Z", PackageID: "G16714158", PackageName: "analysis-pinyin"] - failed
eu-central-1 - OSPackage - G19489597 - [CreatedTime: "2023-10-12T18:27:02Z", PackageID: "G19489597", PackageName: "analysis-nori"] - failed
eu-central-1 - OSPackage - G225801896 - [CreatedTime: "2023-10-12T18:28:25Z", PackageID: "G225801896", PackageName: "analysis-stconvert"] - failed
eu-central-1 - OSPackage - G233213748 - [CreatedTime: "2023-10-12T18:53:02Z", PackageID: "G233213748", PackageName: "analysis-sudachi"] - failed
eu-central-1 - OSPackage - G255846002 - [CreatedTime: "2023-10-12T18:46:29Z", PackageID: "G255846002", PackageName: "analysis-sudachi"] - failed
eu-central-1 - OSPackage - G265292799 - [CreatedTime: "2023-10-12T18:39:06Z", PackageID: "G265292799", PackageName: "analysis-nori"] - failed
eu-central-1 - OSPackage - G32675054 - [CreatedTime: "2023-10-12T18:43:56Z", PackageID: "G32675054", PackageName: "analysis-sudachi"] - failed
eu-central-1 - OSPackage - G39346412 - [CreatedTime: "2023-10-12T18:27:15Z", PackageID: "G39346412", PackageName: "analysis-pinyin"] - failed
eu-central-1 - OSPackage - G42121851 - [CreatedTime: "2023-10-12T18:46:16Z", PackageID: "G42121851", PackageName: "analysis-nori"] - failed
eu-central-1 - OSPackage - G61978666 - [CreatedTime: "2023-10-12T18:49:03Z", PackageID: "G61978666", PackageName: "analysis-pinyin"] - failed
eu-central-1 - OSPackage - G64754105 - [CreatedTime: "2023-10-12T18:25:59Z", PackageID: "G64754105", PackageName: "analysis-nori"] - failed
eu-central-1 - OSPackage - G84610920 - [CreatedTime: "2023-10-12T18:27:27Z", PackageID: "G84610920", PackageName: "analysis-pinyin"] - failed
eu-central-1 - OSPackage - G94746247 - [CreatedTime: "2023-10-12T18:37:04Z", PackageID: "G94746247", PackageName: "analysis-stconvert"] - failed
eu-central-1 - OSPackage - G95833941 - [CreatedTime: "2023-10-12T18:39:44Z", PackageID: "G95833941", PackageName: "analysis-sudachi"] - failed
Removal requested: 0 waiting, 41 failed, 177 skipped, 0 finished
```

**Comment by Tiduster** [comment] 2023-10-18 07:30
Same here.
It started appearing this week, without any change on our AWS accounts or aws-nuke version and config.
Strange!

**Comment by oliverjfletcher** [comment] 2023-10-20 10:02
Seeing the same issue, [this](https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-opensearch-four-language-analyzers/) looks to be the cause and correlates to the date first observed.

**Comment by moltar** [comment] 2023-12-20 11:40
Used this filter to fix it:

```yaml
      OSPackage:
        - type: glob
          value: "G*"
```

![screenshot-20231220T114041-JS8hdWFg@2x](https://github.com/rebuy-de/aws-nuke/assets/491247/8125760f-4154-4191-92c1-c688c8921b4b)

**Comment by ekristen** [comment] 2024-09-14 02:22
This has been fixed in the [actively managed fork of aws-nuke](https://github.com/ekristen/aws-nuke)

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Closed by ekristen** 2024-09-14 02:22 UTC
